version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: timemanager_user
      PGPASSWORD: timemanager_password
      PGDATABASE: timemanager_db
      PGPORT: 5432
    depends_on:
      - db

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: timemanager_user
      POSTGRES_PASSWORD: timemanager_password
      POSTGRES_DB: timemanager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
