# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: # Passa a variável de ambiente para o build do Docker do frontend
        REACT_APP_API_URL: http://localhost:3001/api 
        # Nota: O frontend no browser do usuário acessará o backend via localhost:3001.
        # Se você quisesse comunicação container-para-container (ex: Nginx fazendo proxy),
        # usaria http://backend:3001/api aqui e ajustaria o Nginx.
    ports:
      - "3000:80"
    depends_on:
      - backend
    # A variável de ambiente REACT_APP_API_URL é usada no build do Docker do frontend.
    # Se precisar dela em runtime (improvável para URLs de API no frontend buildado),
    # poderia ser definida aqui também, mas o build é o local correto para Create React App.

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data:/app/data 
    environment:
      - NODE_ENV=production
      - PORT=3001