version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "3000:80" # Assuming same port mapping, can be different if needed
    environment:
      NODE_ENV: production # Or development, as per preference
      # These variables would point to an externally running PostgreSQL instance
      PGHOST: localhost # Or the actual host of the external DB
      PGUSER: timemanager_user
      PGPASSWORD: timemanager_password
      PGDATABASE: timemanager_db
      PGPORT: 5432 # Or the actual port of the external DB
    # No 'depends_on' as the DB is external in this context
    # No 'db' service defined here
    # No top-level 'volumes' needed here unless app itself uses specific named volumes
      
# Note: This compose file is for running the app service independently,
# assuming the database service is managed elsewhere (e.g., by database/docker-compose.yml
# or another method). The PGHOST, PGPORT etc. should be set to match the
# externally available database. For local testing with the root docker-compose.yml,
# PGHOST would ideally be 'db', but for true standalone operation, it would be different.
# For simplicity here, using 'localhost' as a placeholder if one were to run the DB
# directly on the host via its own compose file.
# If this app were to connect to the 'db' service from the root compose, this file isn't strictly needed
# unless for a different deployment scenario.
# The PGHOST is set to 'localhost' assuming the DB started by database/docker-compose.yml
# is mapped to the host's port 5432. If running everything via the root docker-compose.yml,
# the app service there uses PGHOST=db. This file provides an alternative.
# A more robust solution for PGHOST here might involve an override or .env file.
# For this task, will keep it as 'localhost' to signify external DB.
# The instructions said "This compose file assumes the database is running externally",
# so PGHOST=localhost is a reasonable interpretation if the DB's compose maps to host 5432.
# If the DB is also dockerized but separate, it might be an IP or another Docker network alias.
# Let's stick to the spirit: "assumes database is running externally".
# If the database/docker-compose.yml is run, it maps 5432:5432, so PGHOST=localhost for the app here is fine.
